stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    #params:
    #- data_ingestion.test_size
    outs:
    - data/raw 

  pre-processing:
    cmd: python src/pre-processing.py
    deps:
    - data/row
    - src/data_ingestion.py
    #params:
    #- data_ingestion.test_size
    outs:
    - data/interim  

  feature_enginerring:
    cmd: python src/feature_enginerring.py
    deps:
    - data/interim
    - src/feature_enginerring.py
    #params:
    #- feature_engineering.max_features
    outs:
    - data/processed

  model_training:  
    cmd: python src/model_training.py
    deps:
    - src/model_training.py
    - data/processed
    #params:
    #- model_building.n_estimators
    #- model_building.random_stat
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - models/model.pkl
    #params:
    metrics:
    - reports/metrics.json


